---
- name: Configure CentOS 8 VM
  hosts: frontend
  become: true

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

   
